### ISSUE TITLE
Don't include build scripts in package.json for javascript projects

### ISSUE THREAD

**Issue by rahatarmanahmed** [raymond-h/generator-node-module-multilang#19]
They don't do anything, better to remove them than have a dummy script.

**Comment by raymond-h** [comment]
In and of itself, it makes no difference and I don't care either way.

However, the generated package.json file has a `prepublish` script that runs the `build` script. The way it is does make things simpler, but it wouldn't be a big deal to fix.

Either way, with the removal of auto-running lints + tests before building, the `prepublish` script should really be changed, so it runs both `test` (which will run `lint` too) and `build` (possibly skipping `build` for plain JS projects).

**Comment by rahatarmanahmed** [comment]
I know it makes no difference, but it's bound to confuse someone else looking
at the package.json.![](https://link.nylas.com/open/9ldwdqfi9cwauscnezz3xpqle
/local-142c279d-
388f?r=cmVwbHkrMDAzMDZlNzY5YzI0YmNhZGZjNDljNWVmODdiM2VlYTRmYTYxODUyMjhmYTQ5Yjg1OTJjZjAwMDAwMDAxMTM3ZjU3NzI5MmExNjljZTA5OWE5YmNjQHJlcGx5LmdpdGh1Yi5jb20=)

On Jun 20 2016, at 2:04 am, Raymond Hammarling
&lt;notifications@github.com&gt; wrote:  

> In and of itself, it makes no difference and I don't care either way.

>

> However, the generated package.json file has a `prepublish` script that runs
the `build` script. The way it is does make things simpler, but it wouldn't be
a big deal to fix.

>

> Either way, with the removal of auto-running lints + tests before building,
the `prepublish` script should really be changed, so it runs both `test`
(which will run `lint` too) and `build` (possibly skipping `build` for plain
JS projects).

>

> —  
> You are receiving this because you authored the thread.  
> Reply to this email directly, [view it on
GitHub](https://github.com/raymond-h/generator-node-module-
multilang/issues/19#issuecomment-227064913&r=cmVwbHkrMDAzMDZlNzY5YzI0YmNhZGZjNDljNWVmODdiM2VlYTRmYTYxODUyMjhmYTQ5Yjg1OTJjZjAwMDAwMDAxMTM3ZjU3NzI5MmExNjljZTA5OWE5YmNjQHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the thread](https://github.com/notifications/unsubscribe
/ADBudiPjeeE9xe8JRgolOfLoalwtxk-
nks5qNjtygaJpZM4I5Z95&r=cmVwbHkrMDAzMDZlNzY5YzI0YmNhZGZjNDljNWVmODdiM2VlYTRmYTYxODUyMjhmYTQ5Yjg1OTJjZjAwMDAwMDAxMTM3ZjU3NzI5MmExNjljZTA5OWE5YmNjQHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon
/ADBudil6XX_iDimqXU4KIOB-zmOGqYsVks5qNjtygaJpZM4I5Z95.gif)

**Comment by rahatarmanahmed** [comment]
this is a test to see if nylas screws
up![](https://link.nylas.com/open/9ldwdqfi9cwauscnezz3xpqle/local-
a866d1c6-9380?r=cmVwbHkrMDAzMDZlNzY5YzI0YmNhZGZjNDljNWVmODdiM2VlYTRmYTYxODUyMjhmYTQ5Yjg1OTJjZjAwMDAwMDAxMTM3ZjU3NzI5MmExNjljZTA5OWE5YmNjQHJlcGx5LmdpdGh1Yi5jb20=)

On Jun 20 2016, at 2:12 am, Rahat Ahmed &lt;rahatarmanahmed@gmail.com&gt;
wrote:  

> I know it makes no difference, but it's bound to confuse someone else
looking at the package.json.

>

> On Jun 20 2016, at 2:04 am, Raymond Hammarling
&lt;notifications@github.com&gt; wrote:  
>

>

>> In and of itself, it makes no difference and I don't care either way.

>>

>> However, the generated package.json file has a `prepublish` script that
runs the `build` script. The way it is does make things simpler, but it
wouldn't be a big deal to fix.

>>

>> Either way, with the removal of auto-running lints + tests before building,
the `prepublish` script should really be changed, so it runs both `test`
(which will run `lint` too) and `build` (possibly skipping `build` for plain
JS projects).

>>

>> —  
> You are receiving this because you authored the thread.  
> Reply to this email directly, [view it on
GitHub](https://github.com/raymond-h/generator-node-module-
multilang/issues/19#issuecomment-227064913&r=cmVwbHkrMDAzMDZlNzY5YzI0YmNhZGZjNDljNWVmODdiM2VlYTRmYTYxODUyMjhmYTQ5Yjg1OTJjZjAwMDAwMDAxMTM3ZjU3NzI5MmExNjljZTA5OWE5YmNjQHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the thread](https://github.com/notifications/unsubscribe
/ADBudiPjeeE9xe8JRgolOfLoalwtxk-
nks5qNjtygaJpZM4I5Z95&r=cmVwbHkrMDAzMDZlNzY5YzI0YmNhZGZjNDljNWVmODdiM2VlYTRmYTYxODUyMjhmYTQ5Yjg1OTJjZjAwMDAwMDAxMTM3ZjU3NzI5MmExNjljZTA5OWE5YmNjQHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon
/ADBudil6XX_iDimqXU4KIOB-zmOGqYsVks5qNjtygaJpZM4I5Z95.gif)
