### ISSUE TITLE
Create directory if name does not match

### ISSUE THREAD

**Issue by rahatarmanahmed** [raymond-h/generator-node-module-multilang#28]
Current workflow is you `mkdir pkg-name && cd pkg-name && yo node-module-multilang` and it asks u if the name is pkg-name and you're like "yeah".

It might be nice if it asked u "oh your package is called git huh? what a big shot" and you were like "no man its called left-pad it'll be great i promise" and then the generator DIDN'T trash your git folder but instead put everything inside the left-pad dir.

**Comment by raymond-h** [comment]
I think only creating files in the current folder is standard for Yeoman generators, and otherwise might muck with composability of generators.

**Comment by rahatarmanahmed** [comment]
disregard everything
