### ISSUE TITLE
Add test/.eslintrc.json for javascript projects

### ISSUE THREAD

**Issue by rahatarmanahmed** [raymond-h/generator-node-module-multilang#31]
ugh, there's always something, isn't there... 

Javascript projects don't have ES6 enabled in eslint but still use AVA for testing, and eslint flips out. Need to pop in a config for tests for javascript projects.

**Comment by raymond-h** [comment]
We could also consider "plain JS" to essentially mean "ES6 but no need to setup a bunch of tools m8, whatever runs the code handles it", AKA always specify "es6" as an environment in .eslintrc.json.

**Comment by rahatarmanahmed** [comment]
Yeah that's also an option. I mean I still write some modules in ES5 but I
guess it's a matter of what you want as default.
