### ISSUE TITLE
Prettify JSON files

### ISSUE THREAD

**Issue by rahatarmanahmed** [raymond-h/generator-node-module-multilang#32]
Generated json files have lots of weird whitespace due to the templates not putting the newlines themselves inside the if/else statements. We could fix that but then the template code would be ugly af. We should parse and restringify the JSON files so that there's no extra whitespace. I am sure there is a package for this.

**Comment by raymond-h** [comment]
Even better. Looking under "Transform output files through streams" on http://yeoman.io/authoring/file-system.html shows that Yeoman supports running every written file through Vinyl streams (used by Gulp) and then writing them. We can combine a beautifying plugin with a filtering one to automatically beautify all JSON files.
