### ISSUE TITLE
Handle multi word answers

### ISSUE THREAD

**Issue by rahatarmanahmed** [raymond-h/generator-node-module-multilang#37]
Right now you can put spaces in your answers to `What is it called?` and `What is your github username?`.

For `What is it called?`, we should convert that to snake-case before using it in templates.

For `What is your github username?`, probably just need to validate it is a valid username. Not necessarily an existing one, but just one that is valid.

**Comment by nistath** [comment]
This seems easy. Could you point me to the source code that handles the responses? Do you take TypeScript or should I write it directly to js?

**Comment by rahatarmanahmed** [comment]
We'd prefer using ES5 (sorry). You can import something like
`lodash.snakecase` for snakecase-ing. The code that asks the questions is
[here](
https://github.com/raymond-h/generator-node-module-multilang/blob/master/app/index.js#L45-L48),
and the answers are used throughout the templates in `app/templates`.

**Comment by rahatarmanahmed** [comment]
You can check the yeoman documentation on the best way to handle/validate the answers.

**Comment by nistath** [comment]
If you could test this, it'd be great. I don't have time to set up the generator, but the methods I've added should work in their own context.
