### ISSUE TITLE
Parsing error: The keyword 'import' is reserved

### ISSUE THREAD

**Issue by rahatarmanahmed** [raymond-h/generator-node-module-multilang#39]
Getting this from eslint on a fresh generated project.

```
/Users/rahat/git/evolutionary/test/test.js
  1:1  error  Parsing error: The keyword 'import' is reserved
```

**Comment by raymond-h** [comment]
Gonna want to set `parserOptions.sourceType` to `"module"` in eslint config.

Or maybe it's possible to put an eslint config in `test/` and have it inherit everything but `parserOptions.sourceType`, so even if you don't want to use import/export in main code it'll allow it for tests or something.

**Comment by rahatarmanahmed** [comment]
That's probably better, but I could have sworn I already did that?

**Comment by raymond-h** [comment]
[Only for vanilla JS, it seems.](https://github.com/raymond-h/generator-node-module-multilang/blob/master/app/index.js#L179)

**Comment by raymond-h** [comment]
In this case we really probably could just add it into the main config for Babel and Babel for Node 4 projects.

**Comment by rahatarmanahmed** [comment]
I generated a vanilla JS project though.

**Comment by rahatarmanahmed** [comment]
Oh, I did fix this. It just never got published.
