### ISSUE TITLE
Add 'babel-plugin-add-module-exports'

### ISSUE THREAD

**Issue by raymond-h** [raymond-h/generator-node-module-multilang#41]
Add [this](https://www.npmjs.com/package/babel-plugin-add-module-exports) to generated projects maybe? Making modules more compatible with plain CommonJS projects.

**Comment by rahatarmanahmed** [comment]
I don't know about this. You should probably just avoid using `export` for a package's public API (`module.exports` works with cjs and es module syntax). We don't know what interop will look like in the future.
